### ISSUE TITLE
Too many vehicles

### ISSUE THREAD

**Issue by serialtasted** [GreuhZbug/greuh_liberation.Altis#100]
Is it possible to have more infantry coming when the enemy is trying to get the territory back and less armed vehicles? Now that you have the paradrop.

**Comment by GreuhZbug** [comment]
Right now you have the same amount of enemy squads and armed vehicles, the issue is that vehicles are getting there much faster than infantry, giving you the impression that there's less infantry. However infantry use much more cpu power than vehicles, so putting more squads to solve the problem might make the whole experience worse because of crappy performance. I hear your complaint, but the best way to tackle this problem is really not obvious. And I'm pretty sure that if I do find something, other people will complain that there is too much infantry :p

What I can do is to put the amount of infantry and vehicles in the gameplay constants file so you can test different values and find what suits you the most. That's the only way I see to make everyone somewhat happy about it

**Comment by serialtasted** [comment]
That's an excellent solution in fact. Allowing to tweak values

**Comment by serialtasted** [comment]
And, is it normal to have like enemies in multiple objectives trying to take it back? And as soon as we lose one objective the other turns to vulnerable. And this is like in opposite sides of the map. It takes time to get to the objectives, and that makes us lose the control.

**Comment by GreuhZbug** [comment]
Yes if you have several battlegroups attacking your sectors, each will make it's own choices (if I remember my own code, FOBs have priority if the hostiles are within 4km, otherwise they go to the nearest blufor sector)

Allowing the hostiles to capture only one sector at a time is actually a way to prevent you from losing too much too quickly. It wasn't there at first and we lost 10 sectors in only 1 hour on the first test :p

Radio towers should tell you where the hostiles are so you can plan your defence properly, recon also helps. Fast assets such as attack choppers and cas planes can handle the defence if it's on the other side of the map. And to prevent the whole whack-a-mole situation from happening at all, you can also take sectors in the right order so you have only one front line, which makes it much easier to defend. All in all it participates in a strategic aspect of the mission that I don't intend to nerf anytime soon :D

Edit: also, deploying small fobs here and there to serve as redeploy points helps a lot. Just move them as the front line progresses so it doesn't cost you any ammo
