### ISSUE TITLE
F.O.B Object saves bug

### ISSUE THREAD

**Issue by uncookedzebra** [GreuhZbug/greuh_liberation.Altis#101]
I have noticed that after a server restart that fob objects load in improperly. Idk if it has to do with how it is saved or how it is placed . This bug seems to happen when the terrain is uneven.

**Comment by majorwolf** [comment]
@uncookedzebra I have fob objects shift a couple inches or two every restart its just a common thing.

**Comment by uncookedzebra** [comment]
I mean this is kinda drastic almost compromising the base structure so it
needs to be rebuilt. After more tests this happens when objects are on top
of each other even if by just a hair.

**Comment by majorwolf** [comment]
@uncookedzebra from my experience...ZBug has it to where you can't place objects on top of each other. Maybe that's why..

**Comment by GreuhZbug** [comment]
You can place structures on top of each other since they have no physx on them, however maybe the game moves them a bit just to be sure. I usually move an object two times to prevent any colision check to mess with the final position, but maybe in some cases it doesn't work or something

Unless you have a savegame where the problem happens 100% I'll try to put a fob on a mountainside and test what happens
