### ISSUE TITLE
Militia Loadouts

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#31]
What's with the loadouts folder for FIA? Is there something wrong with the vanilla ones? If I wanted to use custom resistance troops, are these loadouts going to be applied to them? What if I am using custom resistance troops alongside RHS mod, are those units going to have RHS rifles instead of those that are designated in their mod config?

There's also an issue when server is running RHS mod and player connects without it, he's not going to hear any gunshots and see any rifles in the hands from the FIA because mission applied RHS loadouts to their units.

**Comment by GreuhZbug** [comment]
RHS doesn't provide any english speaking resistance, and even less "english speaking with a strong greek accent" troops, which is why I'm using default arma 3 guerillas with RHS gear. Now that's a question of taste maybe but I prefer my resistance with crappy AKs and RPGs rather  than the hi-tech gear from vanilla.

I'll tweak the system so it doesn't try to change the loadouts if you're using other resistance troops in your version of the mission.

It's the role of the server admin to enforce mod signatures in the server config, or make sure it's a private server and everyone connects with the same set of mods. There's a client mod that allows the player to execute any script they want and spawn anything they want. In that situation RHS should be the least of your worries. Enforce mod signatures.
