### ISSUE TITLE
Static defenses

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#54]
Add static weapons to the important resource sectors. Like Factories and Military Bases, maybe Radio Towers too.

**Comment by GreuhZbug** [comment]
Too many problems with that :
- making defence way easier when there's already defensive spawns doing most of the job
- having to either save them (scan all sectors -> huge performance problem) or spawn them every time
- ability to pack them and use them as free static weapons anywhere else
- often the spawning of static weapons fail and they pop upside down, that's why i've given up putting them on hostile bases (happens with friendly statics around fobs too)
- in my experience AIs in static launcher are even dumber than usual (they hardly do anything before they die)
- wouldn't know where to put them in good places or which direction to face. More often than not they'd end up facing a wall.
