### ISSUE TITLE
Respawn in water

### ISSUE THREAD

**Issue by asfsdg** [GreuhZbug/greuh_liberation.Altis#60]
After death I respawn very often in water. Sometimes more than 10 times. Sometimes it is working immediatly.
FAR is off, ACE enabled.

**Comment by GreuhZbug** [comment]
Never reproduced in vanilla, so I'm going to guess it's something on your end, especially if you use ACE and/or have modified the mission in some way. Sadly I don't provide support to modded versions because I just don't have enough time.

**Comment by bramjam** [comment]
@asfsdg I have seen this problem before. 
it is caused by mod introduced spawns like Tent objects or camps.
do NOT use anything else than the Liberation build Mobile spawn vehicles/building. 
remove the rest(Tents,Domes,Camps) of the map. restart server . and you should be fine. (don't forget to tell your teammeates)
