### ISSUE TITLE
Cannot build on main altis airport

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#66]
...due to airline lights. This is probably BIS fault, but maybe you can whitelist this entities?
See screenshot
![arma3client_performance_154_133788_v6 2015-12-25 01-26-46-023](https://cloud.githubusercontent.com/assets/84462/11998459/0b1e825c-aab1-11e5-9f7e-38e3f52935b1.jpg)

**Comment by rlex** [comment]
Probably bigger bug than just impossibility to build.
After some time (plane was outside FOB zone) F/A 18 respawned where i spawned it.
I was not able to recycle or enter it.
After i restarted mission, plane was gone and no resources where refunded. 
Can it be bacause of your building system and those blocking entities?

**Comment by rlex** [comment]
This seems to be bugs with modded planes - they disappear after restart no matter where they're placed.
Tested with firewill F-16 and F/A 18, both simply despawned after restart.
Modded helis / IFV are OK with server restart.
I will try with vanilla planes a bit later.

**Comment by GreuhZbug** [comment]
Those mods may have additional scripts that don't like what happens when the savegame system recreates everything. It's often the case with modded airplanes, I remember the black wasp and Su-35 caused a lot of script errors when we were using them. Vanilla planes work as far as I know (we use the buzzard and wipeout)

Your build issue is noted here on trello:
https://trello.com/c/d1od80RW/194-add-airport-lights-to-build-colision-whitelist

(unfortunately linking trello and github is a paid option :p)

Edit: also nope the savegame system doesn't check for colisions at all

**Comment by rlex** [comment]
to not create another ticket: when i kill something with modded plane, it acts like i killed friendly (-1 per exploded tank, for example). Is this mod or mission issue?

**Comment by GreuhZbug** [comment]
I'd call that an historical operation flashpoint issue. When you kill vehicles the game will check the side of the vehicle, not the side of the crew. FIA vehicles (like armed offroads) are considered friendly. CSAT or russian tanks should work correctly.

**Comment by GreuhZbug** [comment]
Issue corrected in v0.919

**Comment by rlex** [comment]
Thank you!

**Comment by rlex** [comment]
Sorry, has to reopen. 0.919:
![2016-01-05_00001](https://cloud.githubusercontent.com/assets/84462/12115364/b6a3ca64-b3c2-11e5-8a13-50ce65b1bda1.jpg)

**Comment by GreuhZbug** [comment]
Yep, you know why, because those damn lights come in several different colors..... x(

**Comment by GreuhZbug** [comment]
Corrected in 0.920
