### ISSUE TITLE
Resource multiplier seems to be affecting CSAT awareness level

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#67]
Not confirmed, but this is the only reason i can imagine.
1) Playing with x2 multiplier
2) Threat level reaches 60%, oh my god, we're all gonna die
3) Spawn FOB mission, destroyed FOB, but got only 20% reduction.

**Comment by rlex** [comment]
On the other side, it is good - you get more resources but you also must work more...
But still, this might be a bug.

**Comment by rlex** [comment]
...or maybe i'm not understanding how it works. 
It dropped by 40% after i reached 100%. Is there some diminishing for smaller awareness level?

**Comment by GreuhZbug** [comment]
The wording I've used seems to cause a lot of confusion, when you complete the secondary objective the alert level is lowered by 40 percent, not 40 points. However since the alert level is expressed in percent, people expect it to drop by the exact amount, which will only happen if you're at 100% indeed.

I'll just think of a better wording but the mechanic is unlikely to change, being able to easily keep at 0% alert would make the mission boring

Edit: unless I've been drinking & coding (which I don't) the resource multiplier has nothing to do with that

combat_readiness = round (combat_readiness \* GRLIB_secondary_objective_impact);
