### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by AlexTriada** [GreuhZbug/greuh_liberation.Altis#86]
Memory leak on clients from FAR revive, not only memory, but cpu usage, after revive always reduced fps

**Comment by AlexTriada** [comment]
Maybe replace far revive with another revive?

**Comment by GreuhZbug** [comment]
That's weird, this revive has been working fine for years now. I'll have a look into it

**Comment by JasonAlanTerry** [comment]
Any insight on this? Need to know before I start dismantling this for other maps.

**Comment by AlexTriada** [comment]
I am not the programmer, but the FAR_revive_init.sqf has a addEventHanler's but not removing they

**Comment by GreuhZbug** [comment]
That's because this event handler is only added once to all playable units when the player connects.

Honestly an issue with FAR revive would make the mission unplayable and all the players would come to me to complain. Since only a handful of people are complaining (and by "handful" I mean two, unless you use different handles and it's only you), then it's pretty obvious the issue is on your end, likely an incompatibility with a mod you're using.

I'd like you to investigate the issue by loading your mods one by one to identify which one is conflicting.

I am not going to divert time from doing features that will benefit every single player to investigate an issue that I can't even reproduce on my end.

Sorry for the tone, but your constant spamming here and on trello is seriously getting on my nerves.

**Comment by AlexTriada** [comment]
no mods

**Comment by GreuhZbug** [comment]
Ok then we're stuck.

**Comment by AlexTriada** [comment]
Ok ... i try disable revive and still the same, sorry, revive no problem
