### ISSUE TITLE
Shift objects after loading server

### ISSUE THREAD

**Issue by AlexTriada** [GreuhZbug/greuh_liberation.Altis#92]
Use getPosWorld, setPosWorld for accurate save and loading objects on the fobs

**Comment by GreuhZbug** [comment]
I don't have this issue since the last change was done, you have a reproduction scenario for this ?

**Comment by AlexTriada** [comment]
Yes, it is!

**Comment by AlexTriada** [comment]
in trello:
Carlos Atanes Vences
[Bug][Ver: 0.921] Some objects like barriers and buildings move when the game is loaded

**Comment by GreuhZbug** [comment]
Again, the issue is not happening on my end. The test case buildings I've put in my savegame when this bug was corrected a few versions back didn't move an inch after hundreds of savegame loads. That's why I'm asking you for a reproduction scenario. I'm afraid I can't do anything if it works fine on my end.

**Comment by AlexTriada** [comment]
what the reproduction? v 0.921 and v 0.922 have this bug

**Comment by AlexTriada** [comment]
"not happening on my end" - this can not be!

**Comment by AlexTriada** [comment]
or you have different version from us

**Comment by AlexTriada** [comment]
I use version from github

**Comment by AlexTriada** [comment]
in my verion on my server i fix this problem using  getPosWorld, and setPosWorld, but you still stubborn, how you wish!

**Comment by AlexTriada** [comment]
You prefer to turn a blind eye to the problem and deny the obvious (( not cool
